### ISSUE TITLE
Load scripts from maps.googleapis.com only after showing the dialog

### ISSUE THREAD

**Issue by smartcorestudio** [ranelpadon/ckeditor-leaflet#15]
Hi Ranel! It's me again! First of all I'd like to tell you some words about my use case. I'd like to use your plugin in my homegrown CMS which I use in my small sites. Sites have many pages and only a few of them (like "Contacts" page, for example) really needs maps. On other pages it's not necessary. So I don't want the addition of new feature negatively affect perfomance. If I add your plugin I can see that many scripts from maps.googleapis.com are loaded on the page load even if I don't open "Create Map" dialog. So I tried to move googleapis loading into the dialog and it seems that it works as I expected:
1) Google scripts are actually loaded only after opening the dialog
2) Google autocomplete works OK
I just moved the line
`	CKEDITOR.scriptLoader.load('//maps.googleapis.com/maps/api/js?libraries=places&callback=dummy&key=...');
`
into the 2nd line of the `Leaflet.js` file. If you want I can make a pull request, but I think you should check everything twice before it and decide is it a good idea or not. I'm not sure, maybe I missed something. You can compare my version here:
http://florako.ru/leaflet/demo/
with yours
http://www.ranelpadon.com/sites/all/libraries/ckeditor/plugins/leaflet/demo/index.html
Look at the "Network" tab of the developer tools

**Comment by ranelpadon** [comment]
Thanks a lot for using my plugin in your homegrown CMS. I've the same thought also before regarding loading the Google JS only when the dialog pops out but I didn't bother to try it. But for now, it's a very good and important idea to minimize the Google API key usage also. I'll try it in my end and check for possible side effects, then I'll come back to you, after that you could create a pull request if you want.

**Comment by smartcorestudio** [comment]
Yeah, I can make a pull request, but I think it's even not necessary, because the idea is very simple - just to move loading of Google JS from one file to another. I hope it won't result in negative side effects, but I'm still not sure. I'm going to release a new version of my CMS soon, so I'm looking forward to the upcoming release of your plugin

**Comment by ranelpadon** [comment]
Okay, sounds a good plan. I've tried moving the script loader to the dialog script, but there's a Console error and Autocomplete will not work. It's the same issue with your website (kindly verify also):

<img width="1437" alt="screen shot 2016-08-12 at 4 58 59 pm" src="https://cloud.githubusercontent.com/assets/4292088/17617183/472aa0ea-60ab-11e6-9e02-41209885541c.png">

And this line is the crux of the issue (at **Line 43** in your leaflet.js):
`// Bind the Search field to the Autocomplete widget.`
`var autocomplete = new google.maps.places.Autocomplete(input);`

since it's inside of dialog's `onShow()` which is immediately triggered, and if the Google JS has not finished loading the objects yet, the `google` undefined error will be fired. But' Ive already some ideas on how to resolve this issue. Solution will revolve on the idea that the critical line should be executed only when the Google script has finished loading. I'll keep you posted.

**Comment by ranelpadon** [comment]
I've already fixed the asynchronous loading issue in this [commit](https://github.com/ranelpadon/ckeditor-leaflet/commit/41d7f76688470f5dd0376ff2fa48df4431f5271a).

Note that I've included you GitHub name as credit in that commit's message. Thanks for your timely and excellent suggestion. I'll update my demo page and include that important change in the **1.7** release, maybe later or tomorrow. Later on if your homegrown CMS is open to public, you could send me a link so that I could include it in the plugin's description and/or README file, just like the `ACTUAL INTEGRATION WITH CMS/FRAMEWORKS` section in my plugin's [CKEditor page](http://ckeditor.com/addon/leaflet). Cheers. :)

**Comment by smartcorestudio** [comment]
Nice catch! I missed this error yesterday, because everything worked OK. But today when I cleared the cache and started from scratch I've got it.
My CMS is not a standalone project and I'm the only man who use it :) But it has it's own support page http://adminpanel.smartcore.ru/ and "Credits" page: http://adminpanel.smartcore.ru/help/credits

**Comment by ranelpadon** [comment]
I've just released CKEditor Leaflet Maps **version 1.7**. Kindly check the further changes in [CHANGELOG](https://github.com/ranelpadon/ckeditor-leaflet/blob/master/CHANGELOG.md), [README](https://github.com/ranelpadon/ckeditor-leaflet/blob/master/README.md), [Installation Notes](https://github.com/ranelpadon/ckeditor-leaflet/blob/master/Installation%20Guide.txt), and project's [CKEditor page](http://ckeditor.com/addon/leaflet). Let me know if you encounter problems. Cheers. :)
