### ISSUE TITLE
After disabling plugin via `config.removePlugins` scripts from maps.googleapis.com are still loaded

### ISSUE THREAD

**Issue by SDKiller** [ranelpadon/ckeditor-leaflet#9]
I wanted to disable plugin in some forms, so I tried

```
config.removePlugins = 'leaflet'
```

Toolbar button disappeared, but there are still plenty of scripts loaded from maps.googleapis.com which affect performance.

Plugin was included by CKEditor builder.

**Comment by ranelpadon** [comment]
Thanks for your feedback, I'll look into it asap.

**Comment by ranelpadon** [comment]
@SDKiller It turned out that the issue only happens when the plugin has been bundled via **CKEditor Builder** and when the **Optimized** version has been selected. 

I've already refactored the code to fix the issue, see commit [here](https://github.com/ranelpadon/ckeditor-leaflet/commit/3d3755f6e5e7eb2fdea8e9d64a6ab1a657ead575). Preliminary testing made the plugin to not load the external scripts anymore. I'll release the fix probably next week. Thanks again for the heads-up.

**Comment by SDKiller** [comment]
That's great news, thanks!

**Comment by ranelpadon** [comment]
Fyi, I've just released version 1.6, which includes the fix for this issue and other improvements/bug fixes. See http://ckeditor.com/addon/leaflet.
